### ISSUE TITLE
How do I exit the browser?

### ISSUE THREAD

**Issue by awkspace** [resin-io-projects/resin-wpe#11]
I've tried a number of key combinations, but I'm still stuck with YouTube TV on my pi.

Am I missing something or is this not documented?

**Comment by petrosagg** [comment]
@awkspace you can't exit the browser because there is nothing else running (like a window manager) to exit to some sort of desktop environment. The browser is running fullscreen and rendering directly to the framebuffer.

To change the URL that is displayed you have to use the `WPE_URL` environment variable as [documented here](https://github.com/resin-io-projects/resin-wpe#loading-a-url)

Can you describe what you're trying to do?

**Comment by awkspace** [comment]
Trying this project out as a replacement for e.g. Links in a framebuffer environment. I want to close the browser and return to the console I was on when I launched it.

So I can start it, but I don't know how to terminate it without doing something like SSH'ing into my Pi and killing the docker container.

**Comment by petrosagg** [comment]
I see. Looking at the sources I don't see anything in place for this kind of behaviour. I think you might be able to do this if you either write a wrapper script or add some wrapper code here https://github.com/WebPlatformForEmbedded/WPEWebKitLauncher/blob/master/launcher/main.cpp#L173 before entering the event loop that will handle keyboard events and will exit the loop on a key combination.

I'd also try opening an issue upstream. I'll close this for now as it's a bit out of scope for this repo
